version: "3.8"

services:
  db:
    image: mariadb:11.4
    container_name: my-mariadb-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: flashcards_db
      MARIADB_USER: flashcard_user
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "flashcard_user",
          "-p${MARIADB_PASSWORD}",
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  backend:
    build: ./backend
    container_name: my-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - /tmp/env/secrets
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_USER=${DB_USER:-flashcard_user}
      - DB_PASSWORD=${MARIADB_PASSWORD}
      - DB_NAME=${DB_NAME:-flashcards_db}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_ISSUER=${CLERK_ISSUER:-https://dear-boar-32.clerk.accounts.dev}
      - DEBUG=${DEBUG:-True}
      - RUNNING_IN_DOCKER=1
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_CLERK_PUBLISHABLE_KEY
    env_file:
      - .env.frontend
      
    container_name: my-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}